# Generated by Django 5.2.10 on 2026-07-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGiro', '0002_vendedor_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='rutaAsignada',
            field=models.CharField(choices=[('Norte', 'Norte'), ('Sur', 'Sur'), ('Este', 'Este'), ('Oeste', 'Oeste')], max_length=100),
        ),
    ]
