# Generated by Django 5.2.10 on 2026-07-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGiro', '0003_alter_vendedor_rutaasignada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rutaId',
            field=models.CharField(choices=[('Norte', 'Norte'), ('Sur', 'Sur'), ('Este', 'Este'), ('Oeste', 'Oeste')], max_length=100),
        ),
    ]
