# Generated by Django 5.2.10 on 2026-07-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGiro', '0005_proveedor_inventario_proveedor_pedido_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='rutaAsignada',
            field=models.CharField(blank=True, choices=[('Norte', 'Norte'), ('Sur', 'Sur'), ('Este', 'Este'), ('Oeste', 'Oeste')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Enviado', 'Enviado'), ('En ruta', 'En ruta'), ('Entregado', 'Entregado')], default='Pendiente', max_length=50),
        ),
    ]
