# Generated by Django 5.2.10 on 2026-07-24 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], max_length=20)),
                ('numero_transferencia', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('En proceso', 'En proceso'), ('Enviado', 'Enviado'), ('En ruta', 'En ruta'), ('Entregado', 'Entregado')], default='En proceso', max_length=20)),
                ('fecha_estimada_entrega', models.DateField(blank=True, null=True)),
                ('numero_contacto', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('nombre_propietario', models.CharField(max_length=50)),
                ('apellido_propietario', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('Mayorista', 'Mayorista'), ('Minorista', 'Minorista')], max_length=20)),
                ('descripcion', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_proveedores/')),
                ('es_verificado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('ruc_rice', models.CharField(blank=True, max_length=13, null=True)),
                ('nombre_tienda', models.CharField(max_length=100)),
                ('nombre_propietario', models.CharField(max_length=50)),
                ('apellido_propietario', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('ubicacion_lat', models.FloatField()),
                ('ubicacion_lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('ruc_rice', models.CharField(blank=True, max_length=13, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=50)),
                ('sector', models.CharField(choices=[('Norte', 'Norte'), ('Sur', 'Sur'), ('Este', 'Este'), ('Oeste', 'Oeste')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_disponible', models.IntegerField()),
                ('stock_minimo_pedido', models.IntegerField()),
                ('unidad_medida', models.CharField(choices=[('Paquete', 'Paquete'), ('Unidad', 'Unidad')], max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.categoria')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='aplicacion.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='aplicacion.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.proveedor'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.tienda'),
        ),
        migrations.CreateModel(
            name='NotificacionTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_ganas', models.TextField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('comision', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_vendedores', to='aplicacion.proveedor')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='aplicacion.vendedor')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.vendedor'),
        ),
    ]
