# Generated by Django 5.2.10 on 2026-07-24 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_proveedor_usuario_tienda_usuario_vendedor_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendida', 'Atendida')], default='Pendiente', max_length=20)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_visita', to='aplicacion.tienda')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_visita', to='aplicacion.vendedor')),
            ],
        ),
    ]
