# Generated by Django 5.2.10 on 2026-07-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_proveedor_usuario_alter_tienda_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='acepta_solicitudes',
            field=models.BooleanField(default=True),
        ),
    ]
