# Generated by Django 5.2.10 on 2026-07-27 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_proveedor_acepta_solicitudes'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvisita',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.proveedor'),
        ),
    ]
