# Generated by Django 5.2.10 on 2026-07-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_solicitudvisita_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numero_contacto',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
