# Generated by Django 5.2.10 on 2026-07-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_alter_pedido_numero_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvendedor',
            name='pago_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='solicitudvendedor',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
